
[general]
# git clone https://github.com/catppuccin/alacritty.git ~/.config/alacritty/catppuccin
# import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
# git clone https://github.com/alacritty/alacritty-theme.git ~/.config/alacritty/themes
import = ["~/.config/alacritty/themes/themes/blood_moon.toml"]
live_config_reload = true
#[color.primary]
#background = "#000918"

[window]
dynamic_title = true
opacity = 0.87
# startup_mode = "Fullscreen"

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 5
y = 0

[scrolling]
history = 100000
multiplier = 5

[font]
size = 18

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font"
# family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 4

# [terminal]
# shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }
